export type BodyType = 'Sedan' | 'Hatchback' | 'Pickup Truck' | 'SUV' | 'MPV'

export type CarColor =
  | 'Silver'
  | 'Black'
  | 'Gray'
  | 'White'
  | 'Gun Metallic'
  | 'Red'
  | 'Blue'
  | 'Yellow'
  | 'Elegant Black'
  | 'Orange'

export interface Car {
  id: string
  year: number
  brand: string
  model: string
  variant: string
  color: CarColor
  bodyType: BodyType
  image?: string
  transmission?: 'Automatic' | 'Manual' | 'CVT'
  engine?: string
  mileage?: number
  price?: number
  negotiable?: boolean
  downpayment?: number
}

export const cars: Car[] = [
  {
    id: '1',
    year: 2023,
    brand: 'Mitsubishi',
    model: 'Mirage',
    variant: 'GLS',
    color: 'Silver',
    bodyType: 'Hatchback',
    image: '/cars/mitsubishi-mirage-gls-2023.jpg',
    transmission: 'Automatic',
    engine: '1.2L MIVEC',
    mileage: 25000,
    price: 480000,
    negotiable: true,
    downpayment: 96000,
  },
  {
    id: '2',
    year: 2024,
    brand: 'Toyota',
    model: 'Vios',
    variant: 'XLE',
    color: 'Black',
    bodyType: 'Sedan',
    image: '/cars/toyota-vios-xle-2024.jpg',
    transmission: 'Automatic',
    engine: '1.5L Dual VVT-i',
    mileage: 12000,
    price: 620000,
    negotiable: true,
    downpayment: 124000,
  },
  {
    id: '3',
    year: 2025,
    brand: 'Honda',
    model: 'City',
    variant: 'S',
    color: 'Gray',
    bodyType: 'Sedan',
    image: '/cars/honda-city-s-2025.jpg',
    transmission: 'CVT',
    engine: '1.5L i-VTEC',
    mileage: 8000,
    price: 650000,
    negotiable: true,
    downpayment: 130000,
  },
  {
    id: '4',
    year: 2018,
    brand: 'Honda',
    model: 'City',
    variant: 'VX',
    color: 'White',
    bodyType: 'Sedan',
    image: '/cars/honda-city-vx-2018.jpg',
    transmission: 'CVT',
    engine: '1.5L i-VTEC',
    mileage: 68000,
    price: 440000,
    negotiable: true,
    downpayment: 88000,
  },
  {
    id: '5',
    year: 2024,
    brand: 'Nissan',
    model: 'Almera',
    variant: 'VE Turbo',
    color: 'Gun Metallic',
    bodyType: 'Sedan',
    image: '/cars/nissan-almera-ve-2024-gunmetal.jpg',
    transmission: 'CVT',
    engine: '1.0L HR10 Turbo',
    mileage: 15000,
    price: 680000,
    negotiable: true,
    downpayment: 136000,
  },
  {
    id: '6',
    year: 2024,
    brand: 'Nissan',
    model: 'Almera',
    variant: 'VE Turbo',
    color: 'Red',
    bodyType: 'Sedan',
    image: '/cars/nissan-almera-ve-2024-red.jpg',
    transmission: 'CVT',
    engine: '1.0L HR10 Turbo',
    mileage: 18000,
    price: 660000,
    negotiable: true,
    downpayment: 132000,
  },
  {
    id: '7',
    year: 2025,
    brand: 'Toyota',
    model: 'Wigo',
    variant: 'G',
    color: 'Silver',
    bodyType: 'Hatchback',
    image: '/cars/toyota-wigo-g-2025.jpg',
    transmission: 'Automatic',
    engine: '1.0L 1KR-DE',
    mileage: 5000,
    price: 420000,
    negotiable: true,
    downpayment: 84000,
  },
  {
    id: '8',
    year: 2023,
    brand: 'MG',
    model: 'GT',
    variant: 'Sport',
    color: 'Blue',
    bodyType: 'Sedan',
    image: '/cars/mg-gt-sport-2023-blue.jpg',
    transmission: 'Automatic',
    engine: '1.5L TGDi Turbo',
    mileage: 22000,
    price: 530000,
    negotiable: true,
    downpayment: 106000,
  },
  {
    id: '9',
    year: 2024,
    brand: 'MG',
    model: 'GT',
    variant: 'Sport',
    color: 'Yellow',
    bodyType: 'Sedan',
    image: '/cars/mg-gt-sport-2024-yellow.jpg',
    transmission: 'Automatic',
    engine: '1.5L TGDi Turbo',
    mileage: 10000,
    price: 560000,
    negotiable: true,
    downpayment: 112000,
  },
  {
    id: '10',
    year: 2023,
    brand: 'GAC',
    model: 'Empow',
    variant: 'GB',
    color: 'Elegant Black',
    bodyType: 'Sedan',
    image: '/cars/gac-empow-gb-2023.jpg',
    transmission: 'Automatic',
    engine: '1.5T TGDi',
    mileage: 30000,
    price: 580000,
    negotiable: true,
    downpayment: 116000,
  },
  {
    id: '11',
    year: 2022,
    brand: 'Ford',
    model: 'Ranger',
    variant: 'Wildtrak 4x2',
    color: 'Orange',
    bodyType: 'Pickup Truck',
    image: '/cars/ford-ranger-2022-orange.jpg',
    transmission: 'Automatic',
    engine: '2.0L EcoBlue Bi-Turbo',
    mileage: 59000,
    price: 980000,
    negotiable: true,
    downpayment: 196000,
  },
  {
    id: '12',
    year: 2024,
    brand: 'Mitsubishi',
    model: 'Triton',
    variant: 'GLS',
    color: 'Black',
    bodyType: 'Pickup Truck',
    image: '/cars/mitsubishi-triton-gls-2024.jpg',
    transmission: 'Automatic',
    engine: '2.4L MIVEC Diesel',
    mileage: 20000,
    price: 1150000,
    negotiable: true,
    downpayment: 230000,
  },
  {
    id: '13',
    year: 2023,
    brand: 'Mitsubishi',
    model: 'Montero Sport',
    variant: 'GLS',
    color: 'White',
    bodyType: 'SUV',
    image: '/cars/mitsubishi-montero-gls-2023.jpg',
    transmission: 'Automatic',
    engine: '2.4L MIVEC Diesel',
    mileage: 16000,
    price: 1080000,
    negotiable: true,
    downpayment: 216000,
  },
  {
    id: '14',
    year: 2024,
    brand: 'Toyota',
    model: 'Innova',
    variant: 'E',
    color: 'Gray',
    bodyType: 'MPV',
    image: '/cars/toyota-innova-e-2024.jpg',
    transmission: 'Manual',
    engine: '2.8L 1GD-FTV Diesel',
    mileage: 22000,
    price: 780000,
    negotiable: true,
    downpayment: 156000,
  },
  {
    id: '15',
    year: 2024,
    brand: 'Nissan',
    model: 'Navara',
    variant: 'VE',
    color: 'Black',
    bodyType: 'Pickup Truck',
    image: '/cars/nissan-navara-ve-2024.jpg',
    transmission: 'Automatic',
    engine: '2.5L YD25DDTi Diesel',
    mileage: 22000,
    price: 1050000,
    negotiable: true,
    downpayment: 210000,
  },
  {
    id: '16',
    year: 2021,
    brand: 'Nissan',
    model: 'Terra',
    variant: 'VE',
    color: 'White',
    bodyType: 'SUV',
    image: '/cars/nissan-terra-ve-2021.jpg',
    transmission: 'Automatic',
    engine: '2.5L YD25DDTi Diesel',
    mileage: 15000,
    price: 980000,
    negotiable: true,
    downpayment: 196000,
  },
  {
    id: '17',
    year: 2023,
    brand: 'Toyota',
    model: 'Hilux',
    variant: 'Conquest 4x4 MT',
    color: 'Silver',
    bodyType: 'Pickup Truck',
    image: '/cars/toyota-hilux-conquest-2023-a.jpg',
    transmission: 'Manual',
    engine: '2.8L 1GD-FTV Diesel',
    mileage: 33000,
    price: 1250000,
    negotiable: true,
    downpayment: 250000,
  },
  {
    id: '18',
    year: 2018,
    brand: 'Isuzu',
    model: 'D-Max',
    variant: 'LSA',
    color: 'Blue',
    bodyType: 'Pickup Truck',
    image: '/cars/isuzu-dmax-lsa-2018.jpg',
    transmission: 'Automatic',
    engine: '3.0L 4JJ1-TC Diesel',
    mileage: 76000,
    price: 720000,
    negotiable: true,
    downpayment: 144000,
  },
  {
    id: '19',
    year: 2023,
    brand: 'Toyota',
    model: 'Hilux',
    variant: 'Conquest 4x4 MT',
    color: 'Red',
    bodyType: 'Pickup Truck',
    image: '/cars/toyota-hilux-conquest-2023-b.jpg',
    transmission: 'Manual',
    engine: '2.8L 1GD-FTV Diesel',
    mileage: 25000,
    price: 1280000,
    negotiable: true,
    downpayment: 256000,
  },
  {
    id: '20',
    year: 2025,
    brand: 'Nissan',
    model: 'Navara',
    variant: 'Calibre',
    color: 'Gray',
    bodyType: 'Pickup Truck',
    image: '/cars/nissan-navara-calibre-2025.jpg',
    transmission: 'Automatic',
    engine: '2.5L YD25DDTi Diesel',
    mileage: 9000,
    price: 1180000,
    negotiable: true,
    downpayment: 236000,
  },
  {
    id: '21',
    year: 2024,
    brand: 'Nissan',
    model: 'Navara',
    variant: 'Calibre',
    color: 'Black',
    bodyType: 'Pickup Truck',
    image: '/cars/nissan-navara-calibre-2024.jpg',
    transmission: 'Automatic',
    engine: '2.5L YD25DDTi Diesel',
    mileage: 6000,
    price: 1120000,
    negotiable: true,
    downpayment: 224000,
  },
]

export const colorConfig: Record<
  CarColor,
  { hex: string; bg: string; text: string; label: string; darkText: boolean }
> = {
  Silver: {
    hex: '#b0b8c1',
    bg: '#e8ecef',
    text: '#5c6470',
    label: 'Silver',
    darkText: true,
  },
  Black: {
    hex: '#222222',
    bg: '#2e2e2e',
    text: '#ffffff',
    label: 'Black',
    darkText: false,
  },
  Gray: {
    hex: '#8d9099',
    bg: '#dde0e4',
    text: '#4a4d54',
    label: 'Gray',
    darkText: true,
  },
  White: {
    hex: '#e8e8e8',
    bg: '#f5f5f5',
    text: '#444444',
    label: 'Pearl White',
    darkText: true,
  },
  'Gun Metallic': {
    hex: '#5a6473',
    bg: '#cdd3da',
    text: '#2e3540',
    label: 'Gun Metallic',
    darkText: true,
  },
  Red: {
    hex: '#c0191f',
    bg: '#f9d5d6',
    text: '#7a0d11',
    label: 'Candy Red',
    darkText: true,
  },
  Blue: {
    hex: '#1d5cc8',
    bg: '#d1defc',
    text: '#0f2d6a',
    label: 'Ocean Blue',
    darkText: true,
  },
  Yellow: {
    hex: '#d4900a',
    bg: '#fdf0c5',
    text: '#7a5200',
    label: 'Solar Yellow',
    darkText: true,
  },
  'Elegant Black': {
    hex: '#111111',
    bg: '#222222',
    text: '#ffffff',
    label: 'Elegant Black',
    darkText: false,
  },
  Orange: {
    hex: '#d4632a',
    bg: '#fde8d8',
    text: '#7a3510',
    label: 'Sunset Orange',
    darkText: true,
  },
}

export const ALL_BRANDS = ['All', 'Mitsubishi', 'Toyota', 'Honda', 'Nissan', 'Ford', 'Isuzu', 'MG', 'GAC']
export const ALL_BODY_TYPES: (BodyType | 'All')[] = ['All', 'Sedan', 'Hatchback', 'Pickup Truck', 'SUV', 'MPV']
